apiVersion: v1
kind: Namespace
metadata:
  name: test-nginx-ingress
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max-demo-lr
  namespace: test-nginx-ingress
spec:
  limits:
  - max:
      memory: 100Mi
      cpu: "100m"
    min:
      memory: 50Mi
      cpu: "50m"
    type: Container
