---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-nginx-ingress
spec:
  selector:
    matchLabels:
      app: MyApp
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        resources:
          limits:
            memory: 80Mi
            cpu: "80m"
          requests:
            memory: 60Mi
            cpu: "60m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: test-nginx-ingress
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      #nodePort: 30007
